# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  pull_request:
    branches: [master, develop]

  push:
    branches: [master, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    services:
      rmq:
        image: rabbitmq
        ports: ["5672:5672"]

    steps:
    - name: Checkout changes
      uses: actions/checkout@main

    - name: Sleep 2s to make rmq start
      run: sleep 2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Setup dependencies
      run: pip install .[tests]

    - name: Check types
      run: mypy --install-types --non-interactive donald 

    - name: Test with Pytest
      run: pytest tests
