# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  pull_request:
    branches: [master, develop]

  push:
    branches: [master, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      rmq:
        image: rabbitmq
        ports: ["5672:5672"]

    steps:
    - name: Checkout changes
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use cache
      id: cache-env
      uses: actions/cache@v2
      with:
        path: env
        key: ${{ runner.os }}-env-${{ hashFiles('setup.cfg') }}

    - name: Setup requirements
      run: |
        python -m venv env
        env/bin/pip install -e .[tests]
      if: steps.cache-env.outputs.cache-hit != 'true'

    - name: Test with Pytest
      run: env/bin/pytest tests
